name: Splunk Reporting
on:
  workflow_run:
    workflows: ["Build and Push to DockerHub"]
    branches: [main]
    types: 
      - completed
jobs:
    Splunk-Report:
        name: "Splunk Reporting"
        #needs: [Polaris-scan,Blackduck-SCA,lint]
        runs-on: ubuntu-latest
        if: always()
        steps:
          - uses: actions/checkout@v2
          - name: Download Artifacts
            if: always()
            uses: actions/download-artifact@v2
            with:
              path: artifacts
          - uses: ./splunk_action/
            with:
              # CONCLUSION: ${{ needs.deploy.result }}
              GITHUB_API_KEY: ${{ github.token }}
              JUNIT_REPORT: jest-junit.xml
              # SPLUNK_API_KEY: ${{ secrets.SPLUNK_API_KEY }}
